### PR TITLE
Laravel 6|7 support

### LINKED ISSUE #23: Compatibility for laravel 6.x^
is there any possibility of having any update to the new version of laravel?

### PR DESCRIPTION
**Pull request by lloricode**
resolve #23

### CODE REVIEW

**Comment by designvoid** [comment]
any chance of this being merged?

**Review by BraulioOC — APPROVED** [review]

**Comment by lloricode** [comment]
can you close this if you dont want to merge?

**Comment by lloricode** [comment]
maintainer not responding

**Review by ulcuber — COMMENTED** [review]
ok

**Pull request closed without merging**
